version: '3.4'
networks:

   frontend:
services:
  middleservice:
    image: middleservice
    build:
      context: .\MiddleService
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development 
    container_name: middleservice
    ports:
      - "55983:80"
    networks:
      - frontend 
